# Generated by Django 5.0.14 on 2026-09-12 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'Student Answer', 'verbose_name_plural': 'Student Answers'},
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
